
package com.pg.ws.stub.calculator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://calculator.demo.service.ws.pg.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param squareOf
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "squareOfResponse", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "squareOfResponse")
    public String squareOf(
        @WebParam(name = "squareOf", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "squareOf")
        String squareOf);

    /**
     * 
     * @param squareRootOf
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "squareRootOfResponse", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "squareRootOfResponse")
    public String squareRootOf(
        @WebParam(name = "squareRootOf", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "squareRootOf")
        String squareRootOf);

    /**
     * 
     * @param convertToHex
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "convertToHexResponse", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "convertToHexResponse")
    public String convertToHex(
        @WebParam(name = "convertToHex", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "convertToHex")
        String convertToHex);

    /**
     * 
     * @param convertToBinary
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "convertToBinaryResponse", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "convertToBinaryResponse")
    public String convertToBinary(
        @WebParam(name = "convertToBinary", targetNamespace = "http://calculator.demo.service.ws.pg.com/", partName = "convertToBinary")
        String convertToBinary);

}
