
package com.pg.ws.stub.calculator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalculatorServiceImplService", targetNamespace = "http://calculator.demo.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/calculator/CalculatorServiceImplService.wsdl")
@HandlerChain(file="config//calculator-handler-chain.xml")
public class CalculatorServiceImplService
    extends Service
{

    private final static URL CALCULATORSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.calculator.CalculatorServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.calculator.CalculatorServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/calculator/CalculatorServiceImplService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/calculator/CalculatorServiceImplService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALCULATORSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public CalculatorServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServiceImplService() {
        super(CALCULATORSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://calculator.demo.service.ws.pg.com/", "CalculatorServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImplPort")
    public CalculatorService getCalculatorServiceImplPort() {
        return super.getPort(new QName("http://calculator.demo.service.ws.pg.com/", "CalculatorServiceImplPort"), CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImplPort")
    public CalculatorService getCalculatorServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calculator.demo.service.ws.pg.com/", "CalculatorServiceImplPort"), CalculatorService.class, features);
    }

}
