
package com.pg.ws.stub.rpclitwrap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RpcLitWrap_Params_ServiceClassService", targetNamespace = "http://wrap.lit.rpc.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/RpcLitWrap/RpcLitWrap_Params_ServiceClassService.wsdl")
public class RpcLitWrapParamsServiceClassService
    extends Service
{

    private final static URL RPCLITWRAPPARAMSSERVICECLASSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.rpclitwrap.RpcLitWrapParamsServiceClassService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.rpclitwrap.RpcLitWrapParamsServiceClassService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/RpcLitWrap/RpcLitWrap_Params_ServiceClassService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/RpcLitWrap/RpcLitWrap_Params_ServiceClassService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RPCLITWRAPPARAMSSERVICECLASSSERVICE_WSDL_LOCATION = url;
    }

    public RpcLitWrapParamsServiceClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RpcLitWrapParamsServiceClassService() {
        super(RPCLITWRAPPARAMSSERVICECLASSSERVICE_WSDL_LOCATION, new QName("http://wrap.lit.rpc.service.ws.pg.com/", "RpcLitWrap_Params_ServiceClassService"));
    }

    /**
     * 
     * @return
     *     returns RpcLitWrapParamsServiceClass
     */
    @WebEndpoint(name = "RpcLitWrap_Params_ServiceClassPort")
    public RpcLitWrapParamsServiceClass getRpcLitWrapParamsServiceClassPort() {
        return super.getPort(new QName("http://wrap.lit.rpc.service.ws.pg.com/", "RpcLitWrap_Params_ServiceClassPort"), RpcLitWrapParamsServiceClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RpcLitWrapParamsServiceClass
     */
    @WebEndpoint(name = "RpcLitWrap_Params_ServiceClassPort")
    public RpcLitWrapParamsServiceClass getRpcLitWrapParamsServiceClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wrap.lit.rpc.service.ws.pg.com/", "RpcLitWrap_Params_ServiceClassPort"), RpcLitWrapParamsServiceClass.class, features);
    }

}
