
package com.pg.ws.stub.hellosecure;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloSecureService", targetNamespace = "http://hellosecure.secure.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/HelloSecure/HelloSecure.wsdl")
public class HelloSecureService
    extends Service
{

    private final static URL HELLOSECURESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.hellosecure.HelloSecureService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.hellosecure.HelloSecureService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/HelloSecure/HelloSecure.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/HelloSecure/HelloSecure.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOSECURESERVICE_WSDL_LOCATION = url;
    }

    public HelloSecureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSecureService() {
        super(HELLOSECURESERVICE_WSDL_LOCATION, new QName("http://hellosecure.secure.service.ws.pg.com/", "HelloSecureService"));
    }

    /**
     * 
     * @return
     *     returns HelloSecure
     */
    @WebEndpoint(name = "HelloSecurePort")
    public HelloSecure getHelloSecurePort() {
        return super.getPort(new QName("http://hellosecure.secure.service.ws.pg.com/", "HelloSecurePort"), HelloSecure.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloSecure
     */
    @WebEndpoint(name = "HelloSecurePort")
    public HelloSecure getHelloSecurePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hellosecure.secure.service.ws.pg.com/", "HelloSecurePort"), HelloSecure.class, features);
    }

}
