
package com.pg.ws.stub.doclitwrap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitWrapServiceClass", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitWrapServiceClass {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.pg.ws.stub.doclitwrap.UserBo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitwrap.GetUserDetails")
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitwrap.GetUserDetailsResponse")
    public UserBo getUserDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        UserBo arg0);

}
