
package com.pg.ws.stub.doclitwrap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitWrap_Params_ServiceClass", targetNamespace = "http://wrap.lit.doc.service.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitWrapParamsServiceClass {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.pg.ws.stub.doclitwrap.UserBo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://wrap.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitwrap.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://wrap.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitwrap.CreateUserResponse")
    public UserBo createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Double arg2);

}
