
package com.pg.ws.stub.doclitwrap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocLitWrap_Params_ServiceClassService", targetNamespace = "http://wrap.lit.doc.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/DocLitWrap/DocLitWrap_Params_ServiceClass.wsdl")
public class DocLitWrapParamsServiceClassService
    extends Service
{

    private final static URL DOCLITWRAPPARAMSSERVICECLASSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.doclitwrap.DocLitWrapParamsServiceClassService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.doclitwrap.DocLitWrapParamsServiceClassService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/DocLitWrap/DocLitWrap_Params_ServiceClass.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/DocLitWrap/DocLitWrap_Params_ServiceClass.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCLITWRAPPARAMSSERVICECLASSSERVICE_WSDL_LOCATION = url;
    }

    public DocLitWrapParamsServiceClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocLitWrapParamsServiceClassService() {
        super(DOCLITWRAPPARAMSSERVICECLASSSERVICE_WSDL_LOCATION, new QName("http://wrap.lit.doc.service.ws.pg.com/", "DocLitWrap_Params_ServiceClassService"));
    }

    /**
     * 
     * @return
     *     returns DocLitWrapParamsServiceClass
     */
    @WebEndpoint(name = "DocLitWrap_Params_ServiceClassPort")
    public DocLitWrapParamsServiceClass getDocLitWrapParamsServiceClassPort() {
        return super.getPort(new QName("http://wrap.lit.doc.service.ws.pg.com/", "DocLitWrap_Params_ServiceClassPort"), DocLitWrapParamsServiceClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocLitWrapParamsServiceClass
     */
    @WebEndpoint(name = "DocLitWrap_Params_ServiceClassPort")
    public DocLitWrapParamsServiceClass getDocLitWrapParamsServiceClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wrap.lit.doc.service.ws.pg.com/", "DocLitWrap_Params_ServiceClassPort"), DocLitWrapParamsServiceClass.class, features);
    }

}
