
package com.pg.ws.stub.doclitwrap.nores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitWrapNoResServiceClass", targetNamespace = "http://nores.wrap.lit.doc.service.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitWrapNoResServiceClass {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setUserDetails", targetNamespace = "http://nores.wrap.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitwrap.nores.SetUserDetails")
    @ResponseWrapper(localName = "setUserDetailsResponse", targetNamespace = "http://nores.wrap.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitwrap.nores.SetUserDetailsResponse")
    public void setUserDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        UserBo arg0);

}
