
package com.pg.ws.stub.doclitwrap.nores;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DocLitWrapNoResServiceClassService", targetNamespace = "http://nores.wrap.lit.doc.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/DocLitWrap/nores/DocLitWrapNoResServiceClassService.wsdl")
public class DocLitWrapNoResServiceClassService
    extends Service
{

    private final static URL DOCLITWRAPNORESSERVICECLASSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.doclitwrap.nores.DocLitWrapNoResServiceClassService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.doclitwrap.nores.DocLitWrapNoResServiceClassService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/DocLitWrap/nores/DocLitWrapNoResServiceClassService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/DocLitWrap/nores/DocLitWrapNoResServiceClassService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DOCLITWRAPNORESSERVICECLASSSERVICE_WSDL_LOCATION = url;
    }

    public DocLitWrapNoResServiceClassService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocLitWrapNoResServiceClassService() {
        super(DOCLITWRAPNORESSERVICECLASSSERVICE_WSDL_LOCATION, new QName("http://nores.wrap.lit.doc.service.ws.pg.com/", "DocLitWrapNoResServiceClassService"));
    }

    /**
     * 
     * @return
     *     returns DocLitWrapNoResServiceClass
     */
    @WebEndpoint(name = "DocLitWrapNoResServiceClassPort")
    public DocLitWrapNoResServiceClass getDocLitWrapNoResServiceClassPort() {
        return super.getPort(new QName("http://nores.wrap.lit.doc.service.ws.pg.com/", "DocLitWrapNoResServiceClassPort"), DocLitWrapNoResServiceClass.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocLitWrapNoResServiceClass
     */
    @WebEndpoint(name = "DocLitWrapNoResServiceClassPort")
    public DocLitWrapNoResServiceClass getDocLitWrapNoResServiceClassPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://nores.wrap.lit.doc.service.ws.pg.com/", "DocLitWrapNoResServiceClassPort"), DocLitWrapNoResServiceClass.class, features);
    }

}
