
package com.pg.ws.stub.doclitbare.inout;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitBare_InOutParam_ServiceClass", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitBareInOutParamServiceClass {


    /**
     * 
     * @param name
     * @param age
     */
    @WebMethod
    @RequestWrapper(localName = "updateUserDetailsInOut", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitbare.inout.UserBo")
    @ResponseWrapper(localName = "updateUserDetailsInOutResponse", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitbare.inout.UserBo")
    public void updateUserDetailsInOut(
        @WebParam(name = "age", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Integer> age,
        @WebParam(name = "name", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> name);

}
