
package com.pg.ws.stub.doclitbare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitWrapServiceClass", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitWrapServiceClass {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.pg.ws.stub.doclitbare.GetUserDetailsResponse
     */
    @WebMethod
    @WebResult(name = "getUserDetailsResponse", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", partName = "parameters")
    public GetUserDetailsResponse getUserDetails(
        @WebParam(name = "getUserDetails", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", partName = "parameters")
        GetUserDetails parameters);

}
