
package com.pg.ws.stub.doclitbare;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitBareServiceClass", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitBareServiceClass {


    /**
     * 
     * @param setUserDetailsNoResp
     */
    @WebMethod
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void setUserDetailsNoResp(
        @WebParam(name = "setUserDetailsNoResp", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", partName = "setUserDetailsNoResp")
        UserBo setUserDetailsNoResp);

    /**
     * 
     * @param name
     * @param age
     * @param salary
     */
    @WebMethod
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitbare.UserBo")
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", className = "com.pg.ws.stub.doclitbare.UserBo")
    public void getUserDetails(
        @WebParam(name = "age", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Integer> age,
        @WebParam(name = "name", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> name,
        @WebParam(name = "salary", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Double> salary);

}
