
package com.pg.ws.stub.doclitbare.noresp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DocLitBareServiceClass", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocLitBareServiceClass {


    /**
     * 
     * @param setUserDetailsNoResp
     */
    @WebMethod
    public void setUserDetailsNoResp(
        @WebParam(name = "setUserDetailsNoResp", targetNamespace = "http://bare.lit.doc.service.ws.pg.com/", partName = "setUserDetailsNoResp")
        UserBo setUserDetailsNoResp);

}
