
package com.pg.ws.stub.webmethod.barestyle;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WS_WebMethods_BareStyleService", targetNamespace = "http://webmethod.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/WebMthOverload/WS_WebMethods_BareStyleService.wsdl")
public class WSWebMethodsBareStyleService
    extends Service
{

    private final static URL WSWEBMETHODSBARESTYLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.webmethod.barestyle.WSWebMethodsBareStyleService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.webmethod.barestyle.WSWebMethodsBareStyleService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/WebMthOverload/WS_WebMethods_BareStyleService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/WebMthOverload/WS_WebMethods_BareStyleService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSWEBMETHODSBARESTYLESERVICE_WSDL_LOCATION = url;
    }

    public WSWebMethodsBareStyleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSWebMethodsBareStyleService() {
        super(WSWEBMETHODSBARESTYLESERVICE_WSDL_LOCATION, new QName("http://webmethod.service.ws.pg.com/", "WS_WebMethods_BareStyleService"));
    }

    /**
     * 
     * @return
     *     returns WSWebMethodsBareStyle
     */
    @WebEndpoint(name = "WS_WebMethods_BareStylePort")
    public WSWebMethodsBareStyle getWSWebMethodsBareStylePort() {
        return super.getPort(new QName("http://webmethod.service.ws.pg.com/", "WS_WebMethods_BareStylePort"), WSWebMethodsBareStyle.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWebMethodsBareStyle
     */
    @WebEndpoint(name = "WS_WebMethods_BareStylePort")
    public WSWebMethodsBareStyle getWSWebMethodsBareStylePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webmethod.service.ws.pg.com/", "WS_WebMethods_BareStylePort"), WSWebMethodsBareStyle.class, features);
    }

}
