
package com.pg.ws.stub.webmethod.barestyle;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WS_WebMethods_BareStyle", targetNamespace = "http://webmethod.service.ws.pg.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSWebMethodsBareStyle {


    /**
     * 
     */
    @WebMethod
    public void publicMth();

    /**
     * 
     * @param publicMthOverloaded
     */
    @WebMethod
    public void publicMthOverloaded(
        @WebParam(name = "publicMthOverloaded", targetNamespace = "http://webmethod.service.ws.pg.com/", partName = "publicMthOverloaded")
        String publicMthOverloaded);

}
