
package com.pg.ws.stub.webmethod;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WS_WebMethodsService", targetNamespace = "http://webmethod.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/WebMthOverload/WS_WebMethodsService_OverloadFixed.wsdl")
public class WSWebMethodsService
    extends Service
{

    private final static URL WSWEBMETHODSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.webmethod.WSWebMethodsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.webmethod.WSWebMethodsService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/WebMthOverload/WS_WebMethodsService_OverloadFixed.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Java_Client/src/main/resources/wsdl/WebMthOverload/WS_WebMethodsService_OverloadFixed.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSWEBMETHODSSERVICE_WSDL_LOCATION = url;
    }

    public WSWebMethodsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSWebMethodsService() {
        super(WSWEBMETHODSSERVICE_WSDL_LOCATION, new QName("http://webmethod.service.ws.pg.com/", "WS_WebMethodsService"));
    }

    /**
     * 
     * @return
     *     returns WSWebMethods
     */
    @WebEndpoint(name = "WS_WebMethodsPort")
    public WSWebMethods getWSWebMethodsPort() {
        return super.getPort(new QName("http://webmethod.service.ws.pg.com/", "WS_WebMethodsPort"), WSWebMethods.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSWebMethods
     */
    @WebEndpoint(name = "WS_WebMethodsPort")
    public WSWebMethods getWSWebMethodsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webmethod.service.ws.pg.com/", "WS_WebMethodsPort"), WSWebMethods.class, features);
    }

}
