
package com.pg.ws.stub.hellomtom;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloMTOMServiceImplService", targetNamespace = "http://hellomtom.mtom.service.ws.pg.com/", wsdlLocation = "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/HelloMTOM/HelloMTOM_DOC_Bare.wsdl")
public class HelloMTOMServiceImplService
    extends Service
{

    private final static URL HELLOMTOMSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.pg.ws.stub.hellomtom.HelloMTOMServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.pg.ws.stub.hellomtom.HelloMTOMServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/HelloMTOM/HelloMTOM_DOC_Bare.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/A:/projects/pgworkspacejee/WS_SOAP_Client/src/main/resources/wsdl/HelloMTOM/HelloMTOM_DOC_Bare.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOMTOMSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public HelloMTOMServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloMTOMServiceImplService() {
        super(HELLOMTOMSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://hellomtom.mtom.service.ws.pg.com/", "HelloMTOMServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns HelloMTOMService
     */
    @WebEndpoint(name = "HelloMTOMServiceImplPort")
    public HelloMTOMService getHelloMTOMServiceImplPort() {
        return super.getPort(new QName("http://hellomtom.mtom.service.ws.pg.com/", "HelloMTOMServiceImplPort"), HelloMTOMService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloMTOMService
     */
    @WebEndpoint(name = "HelloMTOMServiceImplPort")
    public HelloMTOMService getHelloMTOMServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hellomtom.mtom.service.ws.pg.com/", "HelloMTOMServiceImplPort"), HelloMTOMService.class, features);
    }

}
