
package com.pg.ws.stub.hellomtom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloMTOMService", targetNamespace = "http://hellomtom.mtom.service.ws.pg.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloMTOMService {


    /**
     * 
     * @param uploadImg
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "uploadImgResponse", targetNamespace = "http://hellomtom.mtom.service.ws.pg.com/", partName = "uploadImgResponse")
    public boolean uploadImg(
        @WebParam(name = "uploadImg", targetNamespace = "http://hellomtom.mtom.service.ws.pg.com/", partName = "uploadImg")
        byte[] uploadImg);

}
